# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- checkout: self

- script: |
    echo "HELLO FROM NEW PIPELINE"
  displayName: Hello Test